// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmbybahdtigvscsdmcka.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtYnliYWhkdGlndnNjc2RtY2thIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1ODgzOTEsImV4cCI6MjA3MjE2NDM5MX0.2nI2nrtv6WorhBAN2TRPCRvJmlSjzAJnR1lCU4Sgo4c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});